Expose the networking API over HTTP
openSUSE/agama pull request #1064
Opened 2024-03-01 10:12 UTC by teclator

# Implementation PBI description
---

In the previous PBI we documented a possible API and also created a POC but it just allowed to query some configuration, so we have extended the PR with the API implementation

## Implemented Network API

<details>
  <summary>Resource <b>/network/state</b></summary>
  
  - GET: get the current network state and general information 
  
  **Request example**
  
  ```json
$ curl -s localhost:3000/api/network/state -H @headers.txt | j
{
  "connectivity": true,
  "wireless_enabled": false,
  "networking_enabled": true
}
```

  - PUT: Update the current network state (currently only enabling wireless is supported)
  
  **Request example**

  ```json

$ cat state.json 
{
  "connectivity": true,
  "wireless_enabled": true,
  "networking_enabled": true
}
  
$ curl -s -X POST localhost:3000/api/network/state -H @headers.txt -H "Content-Type: application/json" -d @state.json  | jq
{
  "connectivity": true,
  "wireless_enabled": true,
  "networking_enabled": true
}
```
  
</details>
  
<details>
  <summary>Resource <b>/network/devices</b></summary>
  
  - GET: list of known devices
    - Attributes
      - Name: String
      - Type: Enum

**Request example**

```json
$ curl -s localhost:3000/network/devices -H @headers.txt | jq
[
  {
    "name": "enp2s0f0",
    "type": "Ethernet"
  },
  {
    "name": "wlp3s0",
    "type": "Wireless"
  },
  {
    "name": "eth0",
    "type": "Ethernet"
  }
 ``` 
</details>

<details>

<summary>Resource <b>/network/connections</b></summary>

  - GET: list of managed / known connections
  **Request example**
  
  ```json
$curl -s localhost:3000/api/network/connections -H @headers.txt | jq
[
  {
    "id": "lo",
    "method4": "manual",
    "method6": "manual",
    "addresses": [
      "127.0.0.1/8",
      "::1"
    ],
    "interface": "lo"
  },
  {
    "id": "Wired connection 1",
    "method4": "manual",
    "gateway4": "192.168.0.1",
    "method6": "auto",
    "addresses": [
      "192.168.0.230/24"
    ],
    "nameservers": [
      "192.168.0.1"
    ],
    "interface": "eth0"
  },
  {
    "id": "AgamaNetwork",
    "method4": "disabled",
    "method6": "disabled",
    "wireless": {
      "password": "agama.test",
      "security": "wpa-psk",
      "ssid": "AgamaNetwork2",
      "mode": "infrastructure"
    }
  }
]
```

 - POST: create a new connection
 ** Request example **

```json
$ curl -X POST localhost:3000/api/network/connections -H @headers.txt -H "Content-Type: application/json" -d @data_wifi.json
"ce91e1b8-7da4-4bff-a286-91610a8cb762"
```

####  /network/connections/:id
  - GET: find a connection by its uuid or id **(not implemented)**
  - PATCH: update connection
  - DELETE: remove the connection

The attributes for updating a connection or creating a new one could follow the same schema used for the profile:

```json
      "connections": {
        "description": "Network connections to be defined",
        "type": "array",
        "items": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "id": {
              "description": "Connection ID",
              "type": "string"
            },
            "interface": {
              "description": "The name of the network interface bound to this connection",
              "type": "string"
            },
            "mac-address": {
              "description": "Custom mac-address (can also be 'preserve', 'permanent', 'random' or 'stable')",
              "type": "string"
            },
            "method4": {
              "description": "IPv4 configuration method (e.g., 'auto')",
              "type": "string",
              "enum": [
                "auto",
                "manual",
                "link-local",
                "disabled"
              ]
            },
            "method6": {
              "description": "IPv6 configuration method (e.g., 'auto')",
              "type": "string",
              "enum": [
                "auto",
                "manual",
                "link-local",
                "disabled"
              ]
            },
            "gateway4": {
              "description": "Connection gateway address (e.g., '192.168.122.1')",
              "type": "string"
            },
            "gateway6": {
              "description": "Connection gateway address (e.g., '::ffff:c0a8:7a01')",
              "type": "string"
            },
            "addresses": {
              "type": "array",
              "items": {
                "description": "Connection addresses",
                "type": "string",
                "additionalProperties": false
              }
            },
            "nameservers": {
              "type": "array",
              "items": {
                "description": "Nameservers (IPv4 and/or IPv6 are allowed)",
                "type": "string",
                "additionalProperties": false
              }
            },
            "wireless": {
              "type": "object",
              "description": "Wireless configuration",
              "additionalProperties": false,
              "properties": {
                "password": {
                  "type": "string"
                },
                "security": {
                  "type": "string"
                },
                "ssid": {
                  "type": "string"
                },
                "mode": {
                  "type": "string",
                  "enum": [
                    "infrastructure",
                    "adhoc",
                    "mesh",
                    "ap"
                  ]
                }
              }
            },
            "bond": {
              "type": "object",
              "description": "Bonding configuration",
              "additionalProperties": false,
              "properties": {
                "mode": {
                  "type": "string"
                },
                "options": {
                  "type": "string"
                },
                "ports": {
                  "type": "array",
                  "items": {
                    "description": "A list of the interfaces or connections to be bonded",
                    "type": "string",
                    "additionalProperties": false
                  }
                }
              }
            },
            "match": {
              "type": "object",
              "description": "Match settings",
              "additionalProperties": false,
              "properties": {
                "kernel": {
                  "type": "array",
                  "items": {
                    "description": "A list of kernel command line arguments to match",
                    "type": "string",
                    "additionalProperties": false
                  }
                },
                "interface": {
                  "type": "array",
                  "items": {
                    "description": "A list of interface names to match",
                    "type": "string",
                    "additionalProperties": false
                  }
                },
                "driver": {
                  "type": "array",
                  "items": {
                    "description": "A list of driver names to match",
                    "type": "string",
                    "additionalProperties": false
                  }
                },
                "path": {
                  "type": "array",
                  "items": {
                    "description": "A list of paths to match against the ID_PATH udev property of devices",
                    "type": "string",
                    "additionalProperties": false
                  }
                }
              }
            }
          },
          "required": [
            "id"
          ]
```

Which means that for bringing up or down an specific connection / device could need an specific method or it could be handle as any other attribute.
  
  </details>

<deta [...]

2024-03-05 14:49 UTC, imobachgs reviewed
In general, it looks good. The only thing I am not convinced of is to expose the internal model directly. Perhaps we should convert the objects to a `*Settings` object, as we already discussed offline.

2024-03-05 14:49 UTC, imobachgs commented on rust/agama-dbus-server/src/network/action.rs
> +    GetDevice(String, Responder<Option<Device>>),
np: add docs

2024-03-05 14:49 UTC, imobachgs commented on rust/agama-dbus-server/src/network/web.rs
> +    let result = rx.await.unwrap();
You can directly return `Json(result)` as you already get a list of connections. And the same applies to the `devices` method above.

```rust
Json(rx.await.unwrap())
```

2024-03-06 19:37 UTC, teclator commented
> In general, it looks good. The only thing I am not convinced of is to expose the internal model directly. Perhaps we should convert the objects to a `*Settings` object, as we already discussed offline.

Yep, I'm also not convinced about it but as a POC it was good enough.

2024-03-20 14:55 UTC, teclator commented on rust/agama-server/src/network/model.rs
>      ///
`general_state`: General or global network configuration

2024-03-22 07:29 UTC, imobachgs requested changes
Great work! However, I have some comments (as usual) :-) I have not finished the review yet, but you can start looking into the suggestions.

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/model.rs
> +    pub fn new(
We are starting to add quite some parameters. Perhaps we should think about implementing a Builder struct (especially for tests).

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/model.rs
> +impl TryFrom<NetworkConnection> for Connection {
Finding better names for `NetworkConnection` and friends is starting to be urgent. By now, I would import them as `settings::NetworkConnection` to make clear where they come from.

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/model.rs
> +            let method: Ipv4Method = method.parse().unwrap();
I am not sure whether this is the right place to do the parsing. What about doing that in the original `settings::NetworkConnection`? And, of course, `unwrapping` is not an option.

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/model.rs
> +impl TryFrom<Connection> for NetworkConnection {
This file is more than 1200 lines long. What do you think about moving the TryFrom implementation to a separate file? Or, option B, separate the code for each configuration type to its own file.

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/model.rs
> +        let addresses = conn.ip_config.addresses.into();
Are you sure do you need those calls to `into()`? If there are no conversions involved, you should not need them.

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/nm/adapter.rs
> +        Ok(NetworkState::new(
Would not be easier to create a default state and modify things as needed?

```rust
let mut state = NetworkState::default():

if items.contains(&NetworkStateItem::Connection) {
  state.connections = self.client.connections.await().map_err(NetworkAdapterError::Read)?;
}
```

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/web.rs
> +    let conn = NetworkConnection::from(value);
`value` is already a `NetworkConnection` so you do not need to make any conversions.

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/web.rs
> +        .send(Action::AddConnection(
IMHO we should remove the need of having separate actions (`AddConnection` and `UpdateConnection`).

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/web.rs
> +        .send(Action::UpdateConnection(Box::new(conn.clone())))
You can save cloning the whole structure you clone the `uuid` (which is the only thing you need for later).

2024-03-22 07:29 UTC, imobachgs commented on rust/agama-server/src/network/web.rs
> +        .send(Action::UpdateConnection(Box::new(conn.clone())))
No need to clone the connection, right?

2024-03-22 16:16 UTC, teclator commented on rust/agama-server/src/network/action.rs
> +    NewConnection(
I planned to add this new method, but at the end used the AddConnection + UpdateConnection, but as you commented maybe it is the time to remove them and any DBUS specific action.

2024-03-22 16:32 UTC, imobachgs approved these changes

2024-03-22 16:37 UTC, merged