Merged Users and Manager services
openSUSE/agama pull request #596
Opened 2023-05-30 10:49 UTC by mchf

## Problem

Purpose is to save some resources. As there is low benefit from having users in separate process, here it patched to run in same process as the manager service.

- https://trello.com/c/jtFrKeLQ/3348-3-agama-move-users-configuration-to-the-main-service

## Solution

*Short description of the fix.*

## Testing

- *Added a new unit test*
- *Tested manually*

## Screenshots

*If the fix affects the UI attach some screenshots here.*

2023-05-30 10:51 UTC, mchf commented
I've tried to register different objects per Users1 and Agama1. However d-feet shows the same object for both of them

![dbus_users](https://github.com/openSUSE/agama/assets/1579239/a6a60032-ef0f-404f-885f-d4b0844e8ddf)

2023-05-30 15:40 UTC, mvidner commented on service/lib/agama/dbus/manager_service.rb
> +        users_service.export(Agama::DBus::Users.new(Agama::Users.new(logger), logger))
```suggestion
        service.export(Agama::DBus::Users.new(Agama::Users.new(logger), logger))
```

when I do this (which is an obscure workaround!)  it starts to work:

```console
ba3c5497c2c2:/ # abusctl tree org.opensuse.Agama.Users1
Only root object discovered.
```

Oops. Ruby-dbus has a race condition, exposing the service before you export any objects. Let's try again.

```console
ba3c5497c2c2:/ # abusctl tree org.opensuse.Agama.Users1
└─/org
  └─/org/opensuse
    ├─/org/opensuse/Agama
    │ └─/org/opensuse/Agama/Users1
    └─/org/opensuse/Agama1
      └─/org/opensuse/Agama1/Manager
```

2023-06-07 08:33 UTC, imobachgs requested changes
It looks good. Please, add an entry to the `changes` file referencing this PR. Thanks!

2023-06-07 08:33 UTC, imobachgs commented on service/lib/agama/dbus/manager_service.rb
> +      # List of d-bus services exposed by this class
np: D-Bus

2023-06-07 08:34 UTC, imobachgs commented
Please, fix the conflicts too.

2023-06-07 11:53 UTC, imobachgs reviewed
Almost LGTM :-) Just two small things.

2023-06-07 11:53 UTC, imobachgs commented on service/nohup.out
> +
It looks like a left-over 😅

2023-06-07 11:53 UTC, imobachgs commented on service/package/rubygem-agama.changes
> +- Merged Users service into the main one to safe some resources
```suggestion
- Merge the users D-Bus service into the main one to save some resources
  (gh#openSUSE/agama#596).
```

2023-06-07 12:05 UTC, mchf commented on service/nohup.out
> +
ups

2023-06-07 12:38 UTC, imobachgs approved these changes

2023-06-07 12:47 UTC, merged