Form now scrolls up if warning is shown
openSUSE/agama pull request #699
Opened 2023-08-10 22:53 UTC by balsa-asanovic

## Problem

Forms generally show errors on top, so when the submit is clicked again if the error is shown again, it seems as if nothing happens.

fixes #468 

## Solution

I've attached a useRef hook to the alert and whenever the component is rendered with the error it will scroll up to it.

## Testing

No unit test for this component.
Tested manually.

## Screenshots

![image](https://github.com/openSUSE/agama/assets/112288843/35c7c439-d6c8-4098-b0e9-8deb5e40e9d8)
![image](https://github.com/openSUSE/agama/assets/112288843/7237fd61-04e6-4bb7-97ca-948208beb1b1)

2023-08-11 08:32 UTC, imobachgs requested changes
Thanks @balsa-asanovic! The change looks good. Please, add an entry to the [changes file](https://github.com/openSUSE/agama/blob/459221b871eb2ab579bc2ef58c2e56fa80906bed/web/package/cockpit-agama.changes) that includes a reference to the bug (gh#openSUSE/agama#468).

2023-08-12 11:37 UTC, balsa-asanovic commented
@imobachgs added entry to the changes file.

2023-08-12 11:40 UTC, imobachgs commented on web/package/cockpit-agama.changes
> +  the warning shows up after the submit action.
```suggestion
  the warning shows up after the submit action
```

2023-08-12 11:42 UTC, imobachgs approved these changes
Thanks! LGTM. I will merge as soon as the tests run.

2023-08-12 17:20 UTC, merged